name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install
        working-directory: about-me-vue # Run `yarn install` in the `about-me-vue` directory

      - name: Build project
        run: yarn build
        working-directory: about-me-vue # Run `yarn run build` in the `about-me-vue` directory

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ldt"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "about-me-vue/dist" # Specify the build folder to upload
